"""Narration for the parallel Quantum Flow (QFlow) explainer.

Each segment is a list of sentences. `text` is the subtitle. `say` overrides it for
speech synthesis where symbols or acronyms need spoken words; `S` fills it in from SPOKEN.
Numbers trace to arXiv:2606.04186v1 (J. Phys. Chem. Lett., 2026): the introduction for the
logical-qubit projection, Eqs. 1-8 for the method, the Numerical Implementation section for the
workflow, Table 1 for the water basis sets, and the Results section for cycle sizes, convergence,
and propane. The 12-qubit count is 2 x (n_o + n_v) for (n_o, n_v) = (3, 3).
"""

SPOKEN = {
    "QFlow": "Q Flow",
    "ExaChem": "[ExaChem](/ˈɛksəkˌɛm/)",
    "NWQSim": "N W Q Sim",
    "UCCSD": "U C C S D",
    "CCSD": "C C S D",
    "cc-pVDZ": "C C P V D Z",
    "cc-pVTZ": "C C P V T Z",
    "cc-pVQZ": "C C P V Q Z",
    "anti-Hermitian": "anti-[Hermitian](/həɹmˈiʃən/)",
    "1s core": "one S core",
}


def S(text, say=None):
    spoken = say or text
    if say is None:
        for word, sound in SPOKEN.items():
            spoken = spoken.replace(word, sound)
    return dict(text=text, say=spoken) if spoken != text else dict(text=text)


SEGMENTS = [
    ("problem", [
        S("Exact wave-function methods for correlated electrons scale exponentially with system size, so realistic molecules often exceed even the largest supercomputers."),
        S("Quantum computers with about 100 logical qubits are projected for 2028 to 2029, but they may still be too limited to run phase estimation on realistic molecular Hamiltonians."),
        S("Water in the cc-pVQZ basis already needs 228 qubits, and propane in cc-pVDZ needs 164."),
    ]),
    ("idea", [
        S("The Quantum Flow algorithm, QFlow, introduced in earlier work by Kowalski and coworkers, replaces one large problem with many small active-space problems."),
        S("Each active space gets its own downfolded effective Hamiltonian, which includes the effect of the orbitals outside it."),
        S("The qubit count is then set by the largest active space in the flow, not by the whole system."),
    ]),
    ("math", [
        S("QFlow approximates the energy of a unitary coupled cluster state, generated by an anti-Hermitian cluster operator sigma over all orbitals."),
        S("For each active space, sigma splits into an internal part within that space and an external part that reaches outside it."),
        S("With the simplest Trotter approximation, used here, the external part transforms the Hamiltonian, which is then projected onto the active space."),
        S("The internal part is optimized on that small space."),
        S("Each effective Hamiltonian depends on amplitudes, the coefficients in sigma, found in other active spaces, so the problems are coupled."),
    ]),
    ("cover", [
        S("This paper reports a parallel implementation of QFlow for high-performance computers, with single and double excitations, in the ExaChem package."),
        S("A double excitation moves two electrons from two occupied orbitals into two virtual orbitals, so every such group of four must fit inside at least one active space."),
        S("A sampling algorithm draws three occupied and three virtual orbitals at random and keeps the draw only if it covers a new group, until every group is covered."),
        S("The active spaces are sorted from smallest to largest orbital energy difference, and each amplitude belongs to the first one that reaches it, so it is updated once per cycle."),
    ]),
    ("flow", [
        S("An active space of three occupied and three virtual orbitals holds six electrons in six orbitals, which take twelve qubits."),
        S("For each active space, ExaChem builds the effective Hamiltonian on classical processors by double unitary coupled cluster downfolding, using the current global pool of amplitudes."),
        S("The NWQSim simulator then runs a variational quantum eigensolver with a UCCSD ansatz, and the parameters this active space owns update the pool."),
        S("Groups of processors work through the list in parallel, and all of them wait at the end of each cycle before the next one begins."),
        S("Each active space solved later harvests information from those solved before it."),
    ]),
    ("water", [
        S("For water in the cc-pVTZ basis, with the oxygen 1s core uncorrelated, QFlow replaces a 114-qubit problem with cycles of 2,387 twelve-qubit active spaces."),
        S("The pool starts empty, so the first 140 active spaces, one per group, see only the bare Hamiltonian, and the energy falls as amplitudes accumulate."),
        S("By the end of the first cycle, QFlow recovers 95 percent of the correlation energy of the all-orbital CCSD reference."),
        S("From the third to the fourth cycle, every active-space energy changes by less than one millihartree, and from the fourth to the fifth, by only tens of microhartrees."),
    ]),
    ("basis", [
        S("The same convergence holds across five basis sets, up to cc-pVQZ, where cycles of 10,319 active spaces replace a 228-qubit problem."),
        S("The final mean QFlow energy recovers 96.8 to 97.2 percent of the CCSD correlation energy, rising slightly as the basis grows.",
          "The final mean Q Flow energy recovers 96 point 8 to 97 point 2 percent of the C C S D correlation energy, rising slightly as the basis grows."),
    ]),
    ("propane", [
        S("For propane, with all electrons correlated in cc-pVDZ, QFlow replaces the 164-qubit problem with cycles of 56,860 active spaces, which together optimize 1.17 million unique parameters.",
          "For propane, with all electrons correlated in C C P V D Z, Q Flow replaces the 164-qubit problem with cycles of 56,860 active spaces, which together optimize 1 point 1 7 million unique parameters."),
        S("The average reaches 95 percent of the CCSD correlation energy by the third cycle, with every active space converged below one millihartree."),
    ]),
    ("scope", [
        S("All active-space solutions ran on a quantum simulator, and the percentages compare QFlow with CCSD, not with the exact energy."),
        S("Each active space gives its own energy."),
        S("The reported value is their average, a choice suited to the mainly dynamical correlation of these molecules, and other systems may need another."),
        S("The authors expect the remaining correlation to come from a more complete effective Hamiltonian or larger active spaces, and accuracy beyond singles and doubles needs higher excitations."),
    ]),
    ("close", [
        S("In this work, QFlow turned one large simulation into many twelve-qubit problems that run in parallel, and the authors propose it for early fault-tolerant machines, where many shallow active-space circuits could run side by side on a large pool of logical qubits."),
    ]),
]
