"""Narration for the LCHS explainer.

Each segment is a list of sentences. `text` is the caption shown on the website.
`say` overrides it for speech synthesis where symbols need spoken words.
Every number traces to arXiv:2605.10708v3 (Tables 4 and 6-8, Sections 2 and 6.1).
"""

SEGMENTS = [
    ("problem", [
        dict(text="Heat spreading along a rod fades as it spreads."),
        dict(text="Sampled at grid points, the temperatures form a vector u that obeys du/dt = −Au.",
             say="Sampled at grid points, the temperatures form a vector, u, that obeys d u by d t equals minus A u."),
    ]),
    ("split", [
        dict(text="The matrix A splits into a dissipative part L, which is positive semidefinite, and a Hermitian part H."),
        dict(text="L drains the norm of the solution, while H alone would conserve it."),
    ]),
    ("unitary", [
        dict(text="A quantum circuit applies unitary operations, which never change the length of a state vector."),
        dict(text="The solution shrinks, so this evolution cannot be a unitary on the system alone."),
    ]),
    ("lchs", [
        dict(text="Linear combination of Hamiltonian simulation, or LCHS, writes the decaying evolution as a weighted integral over a real variable k.",
             say="Linear combination of Hamiltonian simulation, or L C H S, writes the decaying evolution as a weighted integral over a real variable, k."),
        dict(text="Each k contributes a unitary evolution generated by kL + H, weighted by a kernel g(k).",
             say="Each k contributes a unitary evolution, generated by k L plus H, weighted by a kernel, g of k."),
        dict(text="For a single decay rate λ, every branch only rotates, yet the weighted sum shrinks exactly as e^(−λt).",
             say="For a single decay rate, lambda, every branch only rotates, yet the weighted sum shrinks exactly as e to the minus lambda t."),
    ]),
    ("dv", [
        dict(text="On qubits, the integral becomes a finite quadrature sum."),
        dict(text="An ancilla register indexes the quadrature points and controls every Hamiltonian simulation."),
        dict(text="For the test problems in this paper, the standard sizing rule at accuracy 0.1 calls for 192 to 632 terms on 8 to 10 ancilla qubits.",
             say="For the test problems in this paper, the standard sizing rule at accuracy zero point one calls for 192 to 632 terms on 8 to 10 ancilla qubits."),
    ]),
    ("idea", [
        dict(text="The variable k is continuous, and so is the position of a quantum harmonic oscillator."),
        dict(text="The hybrid construction replaces that register with one oscillator mode and evolves the joint Hamiltonian x̂ ⊗ L + I ⊗ H.",
             say="The hybrid construction replaces that register with one oscillator mode, and evolves the joint Hamiltonian, x hat tensor L, plus H."),
        dict(text="At each position x, the qubits then evolve under the LCHS unitary with k = x.",
             say="At each position x, the qubits then evolve under the L C H S unitary, with k equal to x."),
    ]),
    ("credit", [
        dict(text="This one-mode dilation is shared with Schrödingerisation and qumodisation.",
             say="This one-mode dilation is shared with [Schrödingerisation](/ʃɹˈOdɪŋəɹIzˈAʃən/) and [qumodisation](/kjˈuːmOdIzˈAʃən/)."),
        dict(text="The paper contributes a finite-resource oscillator realization of the LCHS kernel, with an error and cost analysis for each circuit block.",
             say="The paper contributes a finite-resource oscillator realization of the L C H S kernel, with an error and cost analysis for each circuit block."),
    ]),
    ("kernel", [
        dict(text="The kernel enters through two oscillator states, a squeezed vacuum φ and a prepared state ψ, whose wavefunctions multiply to g(x) up to a constant.",
             say="The kernel enters through two oscillator states, a squeezed vacuum, phi, and a prepared state, psi, whose wavefunctions multiply to g of x, up to a constant."),
        dict(text="The circuit prepares ψ, runs the joint evolution, undoes the squeezing, and keeps the runs that find the oscillator in its vacuum state.",
             say="The circuit prepares psi, runs the joint evolution, undoes the squeezing, and keeps the runs that find the oscillator in its vacuum state."),
        dict(text="This postselection evaluates the LCHS integral and leaves the qubits in e^(−At)u₀, up to a known scale factor.",
             say="This postselection evaluates the L C H S integral, and leaves the qubits in e to the minus A t, times u zero, up to a known scale factor."),
    ]),
    ("finite", [
        dict(text="A physical oscillator state needs finite energy, so ψ is built from N squeezed Fock states.",
             say="A physical oscillator state needs finite energy, so psi is built from N squeezed Fock states."),
        dict(text="Truncating the ideal kernel state to N terms leaves an error that falls faster than any power of N, and the paper uses N = 32.",
             say="Truncating the ideal kernel state to N terms leaves an error that falls faster than any power of N, and the paper uses N equals 32."),
        dict(text="The state has stellar rank 31, a measure of its non-Gaussian resource."),
        dict(text="Law–Eberly synthesis prepares it with 31 Jaynes–Cummings pulses and 31 qubit rotations.",
             say="Law Eberly synthesis prepares it with 31 Jaynes Cummings pulses and 31 qubit rotations."),
    ]),
    ("gates", [
        dict(text="Each hybrid term compiles to a displacement of the oscillator controlled by one qubit, wrapped in qubit basis changes."),
        dict(text="A product formula repeats these layers, and the paper bounds the number of steps in terms of evolution time, accuracy, and oscillator cutoff."),
    ]),
    ("postselect", [
        dict(text="Postselection succeeds in about 10 to 16 percent of runs for the four-point heat benchmarks."),
        dict(text="A perturbation bound ties this success probability to the total error of the implemented map."),
    ]),
    ("results", [
        dict(text="Full circuit-level simulations covered heat equations with three boundary conditions, grids of up to 32 points, and non-normal advection–diffusion.",
             say="Full circuit-level simulations covered heat equations with three boundary conditions, grids of up to 32 points, and non-normal advection diffusion."),
        dict(text="Across these one-dimensional cases, the fixed-scale map error stayed at or below 1.48 percent.",
             say="Across these one-dimensional cases, the fixed-scale map error stayed at or below one point four eight percent."),
        dict(text="A four-by-four two-dimensional case, run with parameters chosen on the one-dimensional family, reached 7.40 percent.",
             say="A four by four two-dimensional case, run with parameters chosen on the one-dimensional family, reached seven point four percent."),
    ]),
    ("compare", [
        dict(text="Compared with qubit-only LCHS sized by that rule, one oscillator with 32 coefficients replaces the ancilla register.",
             say="Compared with qubit-only L C H S sized by that rule, one oscillator with 32 coefficients replaces the ancilla register."),
        dict(text="The hybrid route has the smaller fixed-scale error in all ten instances, while the qubit-only route accepts with fewer repetitions in every instance."),
    ]),
    ("close", [
        dict(text="These results support one oscillator mode as an alternative to a discretized ancilla register when quadrature cost dominates, at the price of oscillator operations and extra postselection repetitions."),
    ]),
]
